-- Seed common emojis
INSERT IGNORE INTO `emojis` (`unicode`, `hashedCode`, `name`, `category`) VALUES
('😀', 'grinning-face', 'Grinning Face', 'smileys'),
('😃', 'grinning-face-big-eyes', 'Grinning Face with Big Eyes', 'smileys'),
('😄', 'grinning-face-smiling-eyes', 'Grinning Face with Smiling Eyes', 'smileys'),
('😁', 'beaming-face', 'Beaming Face with Smiling Eyes', 'smileys'),
('😆', 'grinning-squinting', 'Grinning Squinting Face', 'smileys'),
('😅', 'grinning-sweat', 'Grinning Face with Sweat', 'smileys'),
('🤣', 'rolling-on-floor', 'Rolling on the Floor Laughing', 'smileys'),
('😂', 'face-with-tears-joy', 'Face with Tears of Joy', 'smileys'),
('🙂', 'slightly-smiling', 'Slightly Smiling Face', 'smileys'),
('🙃', 'upside-down', 'Upside-Down Face', 'smileys'),
('😉', 'winking-face', 'Winking Face', 'smileys'),
('😊', 'smiling-eyes', 'Smiling Face with Smiling Eyes', 'smileys'),
('😇', 'smiling-halo', 'Smiling Face with Halo', 'smileys'),
('❤️', 'red-heart', 'Red Heart', 'symbols'),
('🧡', 'orange-heart', 'Orange Heart', 'symbols'),
('💛', 'yellow-heart', 'Yellow Heart', 'symbols'),
('💚', 'green-heart', 'Green Heart', 'symbols'),
('💙', 'blue-heart', 'Blue Heart', 'symbols'),
('💜', 'purple-heart', 'Purple Heart', 'symbols'),
('🖤', 'black-heart', 'Black Heart', 'symbols'),
('🤍', 'white-heart', 'White Heart', 'symbols'),
('🤎', 'brown-heart', 'Brown Heart', 'symbols'),
('💔', 'broken-heart', 'Broken Heart', 'symbols'),
('👍', 'thumbs-up', 'Thumbs Up', 'people'),
('👎', 'thumbs-down', 'Thumbs Down', 'people'),
('👏', 'clapping-hands', 'Clapping Hands', 'people'),
('🙌', 'raising-hands', 'Raising Hands', 'people'),
('👋', 'waving-hand', 'Waving Hand', 'people'),
('🤝', 'handshake', 'Handshake', 'people'),
('🙏', 'folded-hands', 'Folded Hands', 'people'),
('🔥', 'fire', 'Fire', 'objects'),
('⭐', 'star', 'Star', 'symbols'),
('✨', 'sparkles', 'Sparkles', 'symbols'),
('💯', 'hundred-points', 'Hundred Points Symbol', 'symbols');
